name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
        working-directory: osid-front

      - name: Start HTTP server
        run: |
          nohup python server.py &
          sleep 5
        working-directory: osid-front

      - name: Health check
        run: curl --fail http://localhost:5000/health
