name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Start Python server
        run: |
          nohup python main.py &   # main.py 가 앱 엔트리포인트라면 여기에
          sleep 5

      - name: Health check
        run: |
          curl --fail http://localhost:5000/health
